### ISSUE TITLE
Logo/Icon Design for Android Weather App

### ISSUE THREAD

**Issue by zularizal** [Bradenm1/Android-weather-app#1]
Hi @Bradenm1 , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by Bradenm1** [comment]
This app won't be on the app store because it won't work soon due to the API. The app was just an assignment for a class I just completed. I uploaded it here to show employers. You can create a logo, icon if you still wish, just the logo and icons may never get seen.

**Comment by zularizal** [comment]
I created a free logo on an open source licensed app.
With the logo will make this application look perfect and iconic. I can put a logo on readme.md. So that can be seen by employers and others.

**Comment by zularizal** [comment]
Sorry, I can't continue.
